backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Dine sider"
    files:
      - file: "src/pages/index.md"
        label: "Forside"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: "Tittel", name: "title", widget: "string" }
          - {
              label: "Undertittel",
              name: "subtitle",
              widget: "string",
              required: false,
            }
          - { label: "Forsidebilde", name: "forsidebilde", widget: image }
          - {
              label: "Firmanavn",
              name: "heading",
              widget: "string",
              required: false,
            }
          - {
              label: "Firmainfo",
              name: "subheading",
              widget: "string",
              required: false,
            }
          - { label: "Mer info", name: "info", widget: "string" }
          - { label: "Bilde", name: "image", widget: "image" }
          - {
              label: "SEO beskrivelse av siden",
              name: "seoDescription",
              widget: "text",
            }
      - file: "src/pages/liftutleie/index.md"
        label: "Liftutleie"
        name: "liftutleie"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden" }
          - { label: SEO beskrivelse, name: seoDescription, widget: string }
          - { label: "Tittel", name: "title", widget: "string" }
          - { label: Forsidebilde, name: forsidebilde, widget: image }
          - {
              label: "Heading",
              name: "heading",
              widget: "string",
              required: false,
            }
          - {
              label: "Subheading",
              name: "subheading",
              widget: "string",
              required: false,
            }
          - { label: "Teknisk info", name: "technicalInfo", widget: "string" }
          - label: "Galleri"
            name: "allImages"
            widget: "list"
            field: { label: Bilde, name: image, widget: image, required: false }
      - file: "src/pages/automatisk-industrimaskin/index.md"
        label: "Automatisk Industrimaskin"
        name: "automatisk-industrimaskin"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "productPage",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: SEO beskrivelse, name: seoDescription, widget: string }
          - { label: Image, name: forsidebilde, widget: image }
          - {
              label: "Heading",
              name: "heading",
              widget: "string",
              required: false,
            }
          - {
              label: "Subheading",
              name: "subheading",
              widget: "string",
              required: false,
            }
          - {
              label: "Teknisk Info",
              name: "technicalInfo",
              widget: "string",
              required: false,
            }
          - label: "Galleri"
            name: "allImages"
            widget: "list"
            field: { label: Bilde, name: image, widget: image }
      - file: "src/pages/rustfritt-rekkverk/index.md"
        label: "Rustfritt Rekkverk"
        name: "rustfritt-rekkverk"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "productPage",
            }
          - { label: "Tittel", name: "title", widget: "string" }
          - { label: SEO beskrivelse, name: seoDescription, widget: string }
          - { label: Forsidebilde, name: forsidebilde, widget: image }
          - {
              label: "Heading",
              name: "heading",
              widget: "string",
              required: false,
            }
          - {
              label: "Subheading",
              name: "subheading",
              widget: "string",
              required: false,
            }
          - {
              label: "Teknisk info",
              name: "technicalInfo",
              widget: "string",
              required: false,
            }
          - label: "Galleri"
            name: "allImages"
            widget: "list"
            field: { label: Bilde, name: image, widget: image }
      - file: "src/pages/kontakt/index.md"
        label: "Kontaktside"
        name: "kontakt"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "contact-page",
            }
          - {
              label: "Sidetittel",
              name: "title",
              widget: "string",
              required: false,
            }
          - {
              label: "Undertittel",
              name: "subtitle",
              widget: "string",
              required: false,
            }
          - {
              label: "SEO beskrivelse",
              name: "seoDescription",
              widget: "string",
            }
          - { label: "Forsidebilde", name: forsidebilde, widget: image }
          - { label: "Adresse", name: "adress", widget: "string" }
          - { label: "Mail adresse", name: "email", widget: "string" }
          - { label: "Mobilnr", name: "phone", widget: "string" }
          - { label: "Telefonnr", name: "phone1", widget: "string" }
          - label: "Ansatte"
            name: "team"
            widget: "list"
            fields:
              - { label: "Navn", name: "name", widget: "string" }
              - { label: "Info", name: "info", widget: "string" }
              - { label: "Bilde", name: "img", widget: "image" }
              - { label: "Telefonnr", name: "mobile", widget: "string" }

      - file: "src/pages/aluminiumsrenner/index.md"
        label: "Aluminiumsrenner"
        name: "aluminiumsrenner"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "productPage",
            }
          - { label: "Tittel", name: "title", widget: "string" }
          - { label: SEO beskrivelse, name: seoDescription, widget: string }
          - { label: Forsidebilde, name: forsidebilde, widget: image }
          - {
              label: "Heading",
              name: "heading",
              widget: "string",
              required: false,
            }
          - {
              label: "Subheading",
              name: "subheading",
              widget: "string",
              required: false,
            }
          - {
              label: "Teknisk info",
              name: "technicalInfo",
              widget: "string",
              required: false,
            }
          - label: "Galleri"
            name: "allImages"
            widget: "list"
            field: { label: Bilde, name: image, widget: image }
      - file: "src/pages/om-oss/index.md"
        label: "Om Oss"
        name: "om-oss"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Sidetittel", name: "title", widget: "string" }
          - { label: Forsidebilde, name: forsidebilde, widget: image }
          - {
              label: Undertittel,
              name: subtitle,
              widget: string,
              required: false,
            }
          - { label: SEO beskrivelse, name: seoDescription, widget: string }
          - {
              label: "Overskrift",
              name: "heading",
              widget: "string",
              required: false,
            }
          - {
              label: "Undertekst",
              name: "subheading",
              widget: "string",
              required: false,
            }
          - {
              label: "Info",
              name: "technicalInfo",
              widget: "string",
              required: false,
            }
          - label: "Produkter"
            name: "products"
            widget: list
            fields:
          - { label: "Tjenester", name: products, widget: list }
          - label: "Ansatte"
            name: "team"
            widget: "list"
            fields:
              - { label: "Navn", name: "name", widget: "string" }
              - { label: "Info", name: "info", widget: "string" }
              - { label: "Bilde", name: "img", widget: "image" }
              - { label: "Telefonnr", name: "number", widget: "string" }
